UPSTASH_REDIS_REST_URL="https://wanted-whale-38572.upstash.io"
UPSTASH_REDIS_REST_TOKEN="AZasAAIncDJmMTk1MGVlNGVjMjk0NDNkOTE3NmQwMGZkODljMDJkNHAyMzg1NzI"
GEMINI_API_KEY="AIzaSyBdJnppnz_8_Z3DHXEF_g7l7w0MdE7HG_A"